name: Validation Checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Validation Checks
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@0f5d171fdb67084a93dd0e545fb68f5b7bbd7e1b # v4.4.0
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check

      - name: Test
        run: npm test
